### ISSUE TITLE
Add map

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#1]
We need a map! We should research good map providers out there, i.e. Google Maps, and see what it takes to integrate them.

**Comment by johnlinahan** [comment]
610d4a5198736dfabf9e73d50bf7b86492d90bcf
Centered it on Oakland's coordinates
[Leaflet](http://leafletjs.com/)
[OpenStreetMap](http://osm.org/) as the map tile layer

**Comment by RitwikGupta** [comment]
I propose using OSM

**Comment by vonbearshark** [comment]
@RitwikGupta aren't we using OSM now for the map tile layer?
