### ISSUE TITLE
Pulling from Pitt event calendars

### ISSUE THREAD

**Issue by seifriedc** [Pitt-CSC/club_project_2017#12]
I think it would be a neat idea if we could pull calendar events from the Pitt Program Council (and/or other calendars) and put them on the map. Not sure if there are APIs for this though. 
Any thoughts?

**Comment by RitwikGupta** [comment]
It seems slightly out of scope for this project to me

**Comment by johnlinahan** [comment]
I think this would be a great addition, but it seems too difficult. If all the maps we pull from used say, Google Calendar, maybe it would be easy to pool them. But PPC, for instance, is not.

**Comment by vonbearshark** [comment]
This seems like an interesting idea, but I also don't think it's in the scope for the semester. Maybe we can work with the groups to standardize the calendars and implement this next year. I'll leave this issue open.
