### ISSUE TITLE
Sidebar on mobile should not be open by default

### ISSUE THREAD

**Issue by kingsman142** [Pitt-CSC/club_project_2017#136]
On mobile, when you load PantherView, the sidebar with checkboxes should be closed by default (there is supposedly code for this in map.js).  However, when I inspect PantherView with Chrome developer tools in mobile view and refresh the page, the sidebar comes open.  I have not tested this on an actual phone but it should produce the same result.

**Comment by seifriedc** [comment]
Yep, can confirm this on iPhone. I'll look into fixing this
