### ISSUE TITLE
Zoom buttons are blocked by "Pitt Data Map" text

### ISSUE THREAD

**Issue by RitwikGupta** [Pitt-CSC/club_project_2017#14]
The zoom buttons are blocked by text, I suggest making a header bar so that can go there.

**Comment by vonbearshark** [comment]
Yeah we need a whole UI. Might have to re-implement our own zoom in and out buttons

**Comment by seifriedc** [comment]
Currenty working on this. I'll make a PR when I get home. Don't have a header made yet but I have removed the text

**Comment by RitwikGupta** [comment]
Cool, reference this issue in the PR and we'll track it till the header's committed!

**Comment by vonbearshark** [comment]
I think we should have the sidebar to the far left, because otherwise we have that weird visual sliver on the left side. If leaflet doesn't provide some way to move around the zoom in/out, we might have to re-implement our own in the sidebar itself.

**Comment by seifriedc** [comment]
Could we slide the sidebar over and change the z-index?

**Comment by vonbearshark** [comment]
You mean overlay the zoom in/out over the sidebar? That would work, but it's messy. The bigger picture is that we want to be able to control where the zoom in/out goes.

**Comment by seifriedc** [comment]
Yeah it does look messy. I figured out how to move the zoom control finally, any preference? I was thinking maybe top right or bottom left corner.

**Comment by vonbearshark** [comment]
Awesome. Both work; make the executive decision, ha.
