### ISSUE TITLE
Global notification

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#16]
We need a global notification system for errors and alerts. Maybe something like [bootstrap alertss](https://v4-alpha.getbootstrap.com/components/alerts/)? Should pop up and disappear on click. Should stack with other errors and notifications, probably.

**Comment by vonbearshark** [comment]
@seifriedc do you want to tackle this? I think you  have a good idea of the UI pieces needed, and we need to get this done early on.

**Comment by seifriedc** [comment]
Yeah sure! I might need some of your guidance though haha. What kinds of errors/messages will we have, like for data retrieval and that sort of stuff?

**Comment by vonbearshark** [comment]
Yeah I actually have two separate Issues for the kinds of info we know we want to notify right now: #31, which is an error thrown when our data doesn't come back as we expected (error) and it should prompt the user to reload that dataset, and #32, which is a notification whenever a dataset is updated (so if you log in the day that the police dataset is updated, then we show a notification that that dataset is fresh).

**Comment by seifriedc** [comment]
Ah ok I see, I'll get on this then. Question: how are we doing error catching/handling? Looks like we are just writing to the console log right now.

**Comment by vonbearshark** [comment]
Right, we'd ideally like to use this Issue with #31. Nothing in place rn

**Comment by vonbearshark** [comment]
@seifriedc We just pulled in a PR that changes how we get the data. There's an empty function `displayNotification` right now that we use--could you work with that one?

**Comment by seifriedc** [comment]
Yeah that works, I'll check it out today when I can

**Comment by seifriedc** [comment]
Ok so I got the boxes and javascript to work I think, but I'm not sure how to get the box to close. Do we just want an X in the corner of each notification box, or do we want to be able to just click/tap inside the box to close it? I think the latter will require jQuery but I'm not sure

**Comment by vonbearshark** [comment]
I think the x in the top right would be perfect
