### ISSUE TITLE
WPRDC Data call function

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#17]
Should create a function to standardize calls to the WPRDC. Should handle generic data errors and special label icons. We have some example calls now.

**Comment by mbilker** [comment]
Something like a 5-second delay then retry the request? I assume using exponential backoff would be a bad idea here.

**Comment by vonbearshark** [comment]
I wonder if we should have the option to provide a callback in the global error management function  (#16), like
> Click to refresh

**Comment by vonbearshark** [comment]
We should have some kind of toggle-able SQL query that could use whatever the given dataset's date field and create a query to get only the results from the past month.

**Comment by vonbearshark** [comment]
@mbilker do you want to tackle this one? You have a good idea of where we want to go with this, and it's important we get this done early on. I'll try and get someone working on #16 for the error notification ASAP

**Comment by mbilker** [comment]
@vonbearshark I can work on this one. Something like a factory function that returns a promise sounds about right for this project.

**Comment by mbilker** [comment]
@vonbearshark could you assign me to this issue?

EDIT: I got the collaboration request email earlier today, but I do not remember if I accepted the invitation properly.

**Comment by vonbearshark** [comment]
All good. Thanks, @mbilker! #16 is now claimed for global notifications, but the Issue for click-reloading on data error that you would want to use here is not. Would you like to claim that, too? (#31.) You'd have to wait until the global notification Issue is filled.  I'll try and get someone to do the pin popup general stylization #26 in the meantime, and we can hook that in as well.

**Comment by vonbearshark** [comment]
Also, in the process of making this function, could you make sure the datasets we have (including the library dataset call that was just created) include use it?

**Comment by mbilker** [comment]
Yeah that is great. I pushed my first try at this and putting up a PR.
