### ISSUE TITLE
Data tab

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#18]
In addition to having a map, we should have another tab that just shows the text results. Should allow you to filter through the data that would otherwise be shown on the map. Similar to a SQL query. Again, similar to the way Burgh's Eye View does it: http://analytics.pittsburghpa.gov/BurghsEyeView/, but ours would be structured slightly differently.

**Comment by vonbearshark** [comment]
@coltonb What do you think about this one? I'm beginning to think this this should be it's own `data.html` page, but on the other hand it would be great if we didn't lose all the data we already loaded into the browser. One idea would be to add all the HTML for the Data tab in the same HTML as the map, but to have Map and Data Tabs (http://www.w3schools.com/bootstrap/bootstrap_tabs_pills.asp) in the sidebar that could be buttons that hide one section of the HTML and show the other. As it stands now, the Date and Legend filters you made could be used in this Data tab, too, to filter the data there. Essentially, we'd just want a non-map list of all the data results, and a searchbar to filter it all out. We'll need a way to generate the HTML for each in the array of markers that we use, too. Each dataset object will probably need a `.popup` function _and_ a `.tableResult` function for this new text results table.

This is a pretty big Issue, so it's going to take a lot of time and back-and-forth. There's no rush

**Comment by seifriedc** [comment]
@vonbearshark I can take this issue

**Comment by seifriedc** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1783783/24150734/f91f8bde-0e1c-11e7-857d-e92fa3350143.png)

@vonbearshark So I'm not sure exactly how you'd like to implement the data table. Currently I'm trying out DataTables, but it uses jQuery. Also I'm not sure what columns we'd like to include. I decided to populate the tables using the `markers` array, which allows us to use the existing filters and filter functions. Now the issue with this is that not all markers have the same data (e.g. non-traffic violations don't even have a date field). So I'm a little stuck in that regard lol but still working on it and I wanted to get your thoughts

**Comment by vonbearshark** [comment]
First, that looks great. It's similar to what I had in mind.

> Currently I'm trying out DataTables, but it uses jQuery

It would be better if we didn't use jQuery. We don't need the pagination that this library offers. We could just have a really big page. I don't know if the search functionality comes with it, but I think we can work around that, too.

> . Also I'm not sure what columns we'd like to include.

If you take a look at the most recent changes we should have some kind of `.table` function for each dataset. It's not your responsibility to determine what properties are being displayed or even how they are displayed, you're just calling that table function on each marker item and putting the resulting returned HTML into the table. Like you said, this lets us use one array and one collection of filtering functions to display everything.

How are you switching between the map and this table page right now? This looks like some kind of overlay. It looks great. Does it navigate back and forth okay?

**Comment by seifriedc** [comment]
Yeah I figured as much but wanted to check with you to make sure! Yes the search comes with it as well. So you're saying there already is a `.table` function for each dataset, or we should eventually do that? I don't see that in the current code.

Currently I have two buttons, Map and Data, on the top of the sidebar. Basically when the user clicks Data, the sidebar extends over the map as an overlay, the sidebar toggle arrow disappears and the table is generated (if it's the first time). Then to get back to the map the user clicks Map, and the sidebar returns to its normal functionality. I'm having a slight issue switching from Data to Map mode but that's only because of the DataTables library I'm using, which we're getting rid of anyways.

**Comment by vonbearshark** [comment]
If it's not there now, it will be, yeah. Just like there is a `popup` function that returns HTML for the map popup, we want a function that will return HTML for a table entry, given a typical data point in a data set.

That's a great solution--I didn't even consider that!

**Comment by seifriedc** [comment]
Oh sweet okay that makes a lot of sense. Thanks! Yeah still working out the kinks but we're making progress haha

**Comment by vonbearshark** [comment]
How's this coming along, @seifriedc?

**Comment by seifriedc** [comment]
I have the table generating and displaying correctly, but I'm having trouble figuring out how to hook it in with our filters. I'll post some code I have and a screenshot in a few minutes when I'm on my laptop. 

Currently I have it just appending rows to the table when we fetch the data, and hiding the table at first obviously. But I'm trying to figure out how to have each row mapped to it's corresponding `record`

**Comment by vonbearshark** [comment]
Yeah that's a good question. I'm wondering if the filter function should throw out the whole table when it's called, then re-generate it every time.

**Comment by seifriedc** [comment]
That might be what we have to do. Ideally I'd like to just `display: none` each filtered table row.

So in data.js I have a `table` field for each dataset like this (just 3 columns as an example):
```javascript
table: (record) => `<td>Non-Traffic Violation</td>
                   <td>${record["OFFENSES"]}</td>
                   <td>${record.incidentMonth}/${record.incidentDay}/${record.incidentYear}</td>
                   <td>${record["NEIGHBORHOOD"]}</td>`
```
Then in main.js, at the end of our `fetch()`:
```javascript
if (dataSource.table) {
  var tr = document.createElement("tr");
  tr.innerHTML = dataSource.table(record);
  document.getElementById("dataTable").appendChild(tr);
}
```
Is there a way we can save a reference to the row in each `marker`/`record`? Or maybe we can give each row an id (doesn't each `record` have one anyways?) and reference the row that way?

This is what it looks like currently:
![4-1](https://cloud.githubusercontent.com/assets/1783783/24582553/1fb38de0-1700-11e7-8d62-9c7431e3176a.png)

**Comment by vonbearshark** [comment]
That's a great system.

I don't think we can assume that each record will get a unique ID. We could probably make one using the datasource name + the index of the record.

Really, it might be cleanest if we just have filter totally toss the table (with something like `innerHTML = ""`) and totally re-write everything. I think you'll find that's actually pretty quick, and it simplifies everything

**Comment by seifriedc** [comment]
Ok I have to adjust my code for the recent PR that was accepted. Do we want Pitt data in the table? Like laundry/labs?

**Comment by vonbearshark** [comment]
No, it's fine without it for now

**Comment by seifriedc** [comment]
Sounds good - think I got it working so I'll submit a PR here soon

**Comment by seifriedc** [comment]
Also I'm working on the data view for mobile currently (not sure if I should make a new issue or not)

**Comment by vonbearshark** [comment]
You can just sub a PR whenever you're ready
