### ISSUE TITLE
Pins

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#2]
We should write a function that will drop pin points of data on the map by location. Should at leats include a color and description, and should be accurate to the latitude and longitude provided.

**Comment by RitwikGupta** [comment]
See PR #9 by @mbilker

**Comment by mbilker** [comment]
The next step should be to provide icons and allow for more datasets than just the 311 data to be displayed.

**Comment by RitwikGupta** [comment]
I don't think that should be the next best step. We should first work on making the function that gets the data robust and able to handle errors and provide feedback in case an error does occur.

**Comment by vonbearshark** [comment]
@RitwikGupta what do you mean? Have one `fetchFromWSPRDC` function that can get all our data from there, and create some kind of standard error function that displays some kind of generic error modal on errors? I think that's a great idea.

@mbilker Do you know if there's some way to filter that 311 data intelligently? I don't see a date field, but there seems to be a "past 100" 311 sub dataset--can you check if we can ping that instead of the full dataset?

**Comment by RitwikGupta** [comment]
@vonbearshark yep! The current one will just silently die if there's an error.

**Comment by mbilker** [comment]
@vonbearshark There is a `CREATED_ON` field that is in a date format. Would have to see if there is a SQL clause to fetch between a certain date range.

From my current knowledge of SQL, a column should be able to be sorted in descending order. From that a number of records can be fetched using a `LIMIT` clause.

**Comment by vonbearshark** [comment]
@RitwikGupta I'll create a UI milestone issue for creating an error display and we'll integrate that, but, yeah, either way we need to have a big function that can call, handle this error or the data, and display a corresponding label for the pin

**Comment by vonbearshark** [comment]
@mbilker those SQL strings seem like something we'll have to write ourselves

Issue for global error object: #16 

Issue for WPRDC data management function: #17

**Comment by mbilker** [comment]
Yes those SQL statements we need to write ourselves. I am looking into what the schema is for the 311 data.

**Comment by vonbearshark** [comment]
I'll create a new series of Issues for the pins themselves (the colors/icons, and the formatted hoverover descriptions), and the data mgmt can be tracked  in #17. I'll consider _this_ one closed from the most recent commit.
