### ISSUE TITLE
Name and Logo

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#23]
So, what should we call this thing? We should get a name, logo, some colors, etc. to define this project

**Comment by nehaabraham** [comment]
How about something to do with the falcons on the Cathedral, Dorothy and E2?

**Comment by vonbearshark** [comment]
Yeah, it might be neat to tie that into the idea that this is a sort-of bird's eye view

**Comment by brlodi** [comment]
Pitt FalconEye \*cue James Bond theme\* (but jokes aside that's a good idea and this is a real suggestion)

**Comment by nehaabraham** [comment]
How's PantherView?

**Comment by mbilker** [comment]
@nehaabraham I think that sounds a little too generic and not a name that really tells what the project is trying to convey.

**Comment by vonbearshark** [comment]
I dunno, I really like PantherView.

What about something like The Oakland Dashboard?

**Comment by mbilker** [comment]
It's not really a dashboard. I like PantherView more than The Oakland Dashboard.

**Comment by brlodi** [comment]
Yeah dashboard implies some sort of control or real-time monitoring interface, not merely a passive aggregation of data.

**Comment by johnlinahan** [comment]
It does sound too generic, but I do like it the most at the same time.
I think we should have Pitt/Panther related word in the name if this is more for Pitt students than Oakland.

**Comment by vonbearshark** [comment]
Alright, PantherView it is! Thanks @nehaabraham !

**Comment by mbilker** [comment]
Nice!
