### ISSUE TITLE
CMU Data?

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#28]
Our friends at the Students for Urban Data Systems at CMU are looking into collecting CMU data. When they give us leads we will need a way to aggregate and visualize this, the same we will do the city and Pitt data. But we still have the question of what data we _want_ to include about CMU?

**Comment by brlodi** [comment]
CMPD jurisdiction overlaps with Pitt PD, and they sometimes deal with Pitt students (fun fact CMU's alcohol amnesty policy applies to Pitt students as long as the calling party or the victim is a CMU affiliate) so if it's possible to get their incident reports with geotags it would be worthwhile including. I know they digitize the reports, but I don't know if they have any coded location information associated with them.

**Comment by vonbearshark** [comment]
Huh, TIL. I'll have SUDS look into the CMPD data
