### ISSUE TITLE
Pitt Data?

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#29]
This is an open ended question, but does anyone know of any interesting University of Pittsburgh data API's that might be cool to hook into this project? Likewise, is there any data that may not be accessible right now that we could look into digitizing?

**Comment by RitwikGupta** [comment]
Ya boi github.com/RitwikGupta/PittAPI

**Comment by RitwikGupta** [comment]
Ya boi https://github.com/RitwikGupta/PittAPI

**Comment by vonbearshark** [comment]
Can we hit that from our JS? Or should we be using it as an example for how to make those calls, the data format, etc.? Either way, I think the laundry and computer lab would be dope. I'll create Issues for the UI and data around those two for sure

**Comment by RitwikGupta** [comment]
I have a Flask web wrapper that used to serve endpoints for the API (https://github.com/RitwikGupta/PittAPIWebWrapper). George took it down from the CSC site but we can put it back up.

**Comment by vonbearshark** [comment]
Why did we take it down? Wait, we have a server?

**Comment by RitwikGupta** [comment]
Apparently we have a DigitalOcean droplet

**Comment by RitwikGupta** [comment]
And we took it down because no one was using it at the time, but I think more people are just hosting it personally at the moment.

**Comment by vonbearshark** [comment]
Good to know. We could hit that API, but that would be a call out to another call? Would it be too much to redo in JS?

**Comment by RitwikGupta** [comment]
No, it's a call that does the scraping/intercepting/cleaning and returns results to you. No other intermediary calls. It's just exposing those Python library calls to the web.

**Comment by RitwikGupta** [comment]
It might be too much. There's some web scraping mixed in with interpreting the data protocol that the 3rd-party contractors use.

**Comment by vonbearshark** [comment]
That's interesting. I'm wondering if we should try and absorb your Pitt API project and host it as the club. Like, the club becomes an owner and part of this project could be for members to build the API/Flask services. Any new Pitt Data we could channel through that.

Either way we could kick out to the Pitt API (wherever it ends up being) one kind of function like we will  have for the WPRDC in #17. Helps us standardize the frontend.

**Comment by RitwikGupta** [comment]
I think that would be terrific. It's kind of what ScottyLabs at CMU does.

**Comment by vonbearshark** [comment]
Are you an owner for the club, @RitwikGupta? Do you want to add the CSC as an owner for the API and the Flask wrapper? We should also probably deploy it on our DO droplet--do you have the creds for that?

**Comment by RitwikGupta** [comment]
I don't have the DO creds. You'll have to ping George for that.

**Comment by vonbearshark** [comment]
Looks like studentprojects.sis.pitt.edu works, but fwiw the auth for that is on the Drive

**Comment by RitwikGupta** [comment]
Closing this since it's elaborated in separate issues.
