### ISSUE TITLE
Map interface

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#3]
The map needs a user interface overlay. Something to filter out pins, etc.

**Comment by seifriedc** [comment]
Working on side bar currently. Have we nailed down some of the filters we'll be doing?

**Comment by vonbearshark** [comment]
Thanks @seifriedc ! Good question... We're a little hamstrung by the data available with the WPRDC in the API. I'd like to say by date (past day, week, month), but I don't know that date data is available. Any ideas?

**Comment by RitwikGupta** [comment]
Date data exists in every single report object!

**Comment by vonbearshark** [comment]
So far, yeah. I'm looking through the other data we know we will be using, and it looks like these also have date info. So we'll need sorting by date for at least most of the datasets

**Comment by seifriedc** [comment]
Perfect, I'll get on that then

**Comment by vonbearshark** [comment]
Oh, and we'll want to filter the datasets themselves, and toggle which ones are visible.

**Comment by vonbearshark** [comment]
This is a big Issue that I'd like to break up into smaller ones. So I'll close this out on your latest commit and start new ones
