### ISSUE TITLE
Data Error Global notitfication

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#31]
We need an error display for the data. Should pop up, but shouldn't kill the whole application. Hooks into our global alert system #16. So it needs that to proceed

**Comment by vonbearshark** [comment]
In our `fetchWPRDCData` function, we want to throw and error if we don't get a 200 response and catch all errors from the `fetch` promise. That catch should absorb the _true_ error, though, and just display that the dataset name could not be loaded. It should also have an icon button to click to try and reload that data (which can call a one-off `fetchWPRDCData` function, just like it was originally called)

**Comment by vonbearshark** [comment]
Hey @seifriedc , do you think you can tackle this one next? This hooks right into the global notification you just made

**Comment by seifriedc** [comment]
Yep I was actually just looking at this issue, you can assign me

**Comment by vonbearshark** [comment]
Hey @seifriedc, @mbilker just subbed a PR that took care of some of this for you. Take a look at the most recent changes. In addition to what @mbilker has, we want to show _which_ datasource fails, and provide the function that adds a button to retry fetching the dataset. Also I think the notification type param might be off.

**Comment by mbilker** [comment]
Oh sorry. I forgot about his issue. I just published my take on where stuff should go.

**Comment by seifriedc** [comment]
Do we want to display something if we don't get a good response, if we can't make a record, or both?

**Comment by vonbearshark** [comment]
Both, I think. If we don't get a good response, the error should be "Could not retrieve [datasourcename]", and if we can't format every record, the error should be "Problem formatting [datasourcename]", or something, I think.

**Comment by seifriedc** [comment]
Ok sounds good. Now I'm having a problem where if we don't get a good response, both error boxes come up. Is that how we want it?

**Comment by vonbearshark** [comment]
Ha, uh, I don't think so. I'm not sure how we have it now, but the response check should actually _throw_ an error, rather than return it. That should trigger the _catch_. Likewise, I think the way we have it, if the status is good we return `response` rather than `response.json()` (and have `response.json()` in another `.then`). I think we can compact that into the `else` statement in the first `.then`

**Comment by seifriedc** [comment]
Ohhh my bad okay that makes sense. So I have it throwing and catching correctly I think. I'm a little confused on the `response.json()` bit though. We want to put `.then((response) => response.json())` into the `else` above it? Right now I have this:
```
} else {
    (response) => response.json();
    throw "Could not retrieve " + dataSourceName + " dataset";
}
```
but I'm not sure if I'm doing it right.

**Comment by vonbearshark** [comment]
That's close. It should be something like:
```
//if res is between 200 and 300, or whatever:
{
    return response.json(); // this will send the json response further down the pipelin on success, so we can remove the next .then() completely
}
} else {
    throw new Error("Could not retrieve the " + dataSourceName + " dataset");
}
```

**Comment by seifriedc** [comment]
Ok cool yeah that's what I thought you meant at first. Also (sorry to keep bothering you) when we catch an error, it seems to kill the filters in the sidebar. Should we separate the filter display code and filter/record logic?

**Comment by vonbearshark** [comment]
No worries, this should be a back-and-forth process for sure.

Yeah that's going to be a little messy. My thinking is that if we get the data as JSON and it _has_ an array of records, we can probably defer to the `processRecord` of each record to catch and (probably silently) handle their own errors. I know it's probably not a robust way to handle it, but we don't want to throw an Error when the record isn't exactly aligned, I don't think--rather, we should individually handle all the places it could be misaligned. You don't have to worry about that; just make sure we have an array of records; if we don't have that then we should definitely throw and error (before we add to the sidebar). Does that break anything?

**Comment by seifriedc** [comment]
So I'm checking if `records == null`, and if it that is true then we throw the error and no filters show up in the sidebar :/

**Comment by vonbearshark** [comment]
The thrown Error must not be getting caught by the `.catch`. Technically, `.catch` should catch rejected promises, not necessarily errors. So we can throw in the first `.then`, but not here when we're checking the `data`. Here we should just use a simple `if(whatever.records)` and `else { displayErrorFunction() }`. So rather than throwing an Error in that else, we just call the notification ourselves and don't do any of the actual processing.

**Comment by mbilker** [comment]
The `.catch` caught the errors when I used a `currentDate` when it was `undefined`. The reason why Promises catch `Error`s is to make it easier to `throw` and `catch` errors than using `try { ... } catch (e) { ... }`.

**Comment by vonbearshark** [comment]
Right. There's some cases where Errors are thrown that `.catch` doesn't catch, like asych stuff, or after promise resolution. This could be the latter case.

**Comment by mbilker** [comment]
EDIT: **Discussed with JJ**
There is something going on here with promise resolve and error handling. I devised a test case and the only case that can cause the issues you are seeing are `new Promise` or async stuff like `setTimeout` or `setInterval`.

**Comment by mbilker** [comment]
Also, I did make a mistake with calling `displayNotification` directly from the HTTP error response handler. It should `throw error;`.

**Comment by seifriedc** [comment]
Do we want to do anything for `Promise.all([...]).catch()`? Right now we just have `console.log`

**Comment by mbilker** [comment]
I assume that we are going to do something to display a notification that
something really bad has happened.

That last catch should be a last resort. Catches before it will handle
errors on a more specific basis for things like request retry timeout and
displaying more relevant notifications about an error.

**Comment by vonbearshark** [comment]
^. We could maybe have a "retry" button for that, too, and that just re-tries the whole `Promise.all`
