### ISSUE TITLE
New Data notification

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#32]
Should have a global notification that shows when new data has been created at the WPRDC. This should be a part of the global notification system (#16), so it needs that to proceed. Should also check in the WPRDC data grab function (#17 ) for the last updated information

**Comment by vonbearshark** [comment]
@seifriedc , you might as well take this one, too, haha.

**Comment by seifriedc** [comment]
Sounds good, thanks!

**Comment by vonbearshark** [comment]
@saylorsd do you know how we can get the date the set has been modified? Does that come from the same endpoint? Seems like we only get the data right now

**Comment by saylorsd** [comment]
The `resource_show` endpoint is probably what you're looking for.  It will give you metadata on a resource including the modified timestamp.

You can check it out for the [air quality daily summary resource](https://data.wprdc.org/dataset/allegheny-county-air-quality/resource/7a417847-37bb-4a16-a25e-477f2a71661d) here: https://data.wprdc.org/api/action/resource_show?id=7a417847-37bb-4a16-a25e-477f2a71661d

**Comment by seifriedc** [comment]
Thanks @saylorsd ! I'm not sure exactly how to test my code in this case but I'll submit a PR and you can take a look @vonbearshark

**Comment by saylorsd** [comment]
@seifriedc If the testing issue is waiting for an update, 311 will update every hour (except possibly at night when there is no new data).

**Comment by seifriedc** [comment]
Ah good to know, thank you
