### ISSUE TITLE
Laundry Data

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#33]
Pitt has an API for laundry--let's use it! Since this doesn't come from the WPRDC, this can be a one-off call for this data, but like the WPRDC data call function (#17). This won't display pins, so let's just focus on getting the data, and go from there

**Comment by vonbearshark** [comment]
@SPN11 This should be just like you did with #35

**Comment by SPN11** [comment]
This one checks out on all requirements (in comparison to something like #35 ), and I de-duplicated some code for `fetchPittData()` as that is also where I put the laundry code. Also fixed some error handling.

**Comment by vonbearshark** [comment]
This looks awesome. If only we had a server...

**Comment by Rahi374** [comment]
https://github.com/Pitt-CSC/PittAPI/blob/master/PittAPI/laundry.py

**Comment by Rahi374** [comment]
I thought we added this to PittAPI already?

**Comment by vonbearshark** [comment]
I hope so or this code wouldn't work, haha. The PittAPI has the actual call for the laundry data. This is the user interface for accessing that data, which involves calling the PittAPI server from the browser. Except we don't _have_ the server access yet.

**Comment by Rahi374** [comment]
Oooooh
I thought we got a server already

**Comment by SPN11** [comment]
If we want we can merge it in and comment out all the `fetchPittData()` function calls in `fetchAllData()` until we have the server, then just edit the URLs in `fetchPittData()` and uncomment the calls once we do (Just so we aren't always getting those ugly errors when we load PantherView). Speaking of URLs, @RitwikGupta what would be the base URL to fetch laundry data from the API?

**Comment by RitwikGupta** [comment]
Would be `/laundry/simple/<location>` or `/laundry/detailed/<location>` depending on the info you want

**Comment by SPN11** [comment]
Would you want me to use simple or detailed for this? And I meant what would the domain be? Haha sorry I should have been more specific. I mean we don't have the server yet but just for future reference if you know.

**Comment by RitwikGupta** [comment]
Domain still isn't decided yet. And it's up to you what you want to use. I think `simple` is probably closest to what you need.

**Comment by SPN11** [comment]
Cool! I used `simple` for now, but if we want to later I can do `detailed`
