### ISSUE TITLE
Computer Labs Visual

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#36]
Similar to the laundry API (#34), there is a n API for the computer labs on Pitt's campus. This isn't a pin, but maybe there is a pin that we click that opens up a pop-up modal that lists the status of the lab. Maybe instead there is a separate tab or page for this. I'm not sure, but I'm open to suggestions

**Comment by brlodi** [comment]
Is there any documentation for these APIs? What's the endpoint?

**Comment by brlodi** [comment]
Oh is the plan scraping from <http://labinformation.cssd.pitt.edu>? (thanks @RitwikGupta)

**Comment by vonbearshark** [comment]
This is something that

**Comment by vonbearshark** [comment]
Woops. This is something that @RitwikGupta , @JohnLinahan, and I have been talking about lately. There's a lot of Pitt APIs that are not well maintained, or involve scraping, etc. Our plan is to have an additional project that is a Flask wrapper around a library that could organize all these calls. For now, the library is here: https://github.com/Pitt-CSC/PittAPI and the Flask Wrapper is here: https://github.com/Pitt-CSC/PittAPIWebWrapper . We haven't figured out a hosting solution yet (looking to get on a dept server), but we're working on it.

**Comment by vonbearshark** [comment]
Not only a popup, but when we create the Data Tab (#18), we'll need to find some way to display this information in the table results. And the larger question is: how do we want to handle this kind of data in that data tab? I'm wonder if we have a search bar to search through the pin-based data, but this kind of data without a date (like the library, healthy ride, laundry data, etc.) could each get their own sub-tab with a whole display. This would quell a lot of debate we had about this kind of data being its own application, because we can visualize it in a more meaningful way here.

**Comment by vonbearshark** [comment]
Closed by #129
