### ISSUE TITLE
Sidebar: filter data shown

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#37]
In our sidebar, we should be able to filter the data that shown. For example, for right now we would want to be able to filter out either the 311 data or the city police data (or both if we just want to show the map).

**Comment by vonbearshark** [comment]
We should have a legend that shows what colors/icons correspond to what kind of data. Should match up with #25. Should be able to toggle from this legend what datasets are shown.

**Comment by vonbearshark** [comment]
@CJB124 : any chance you can apply your filter-data-with-ui magic here, too?

**Comment by vonbearshark** [comment]
We'll have a PR coming in that will make it easy to list all the datasets with their corresponding pins

**Comment by coltonb** [comment]
Sure, I can give it a try.

**Comment by vonbearshark** [comment]
Thanks, @CJB124 ! We just pulled in the latest PR. Pull the changes to see the new system for getting the data. Should be able to loop over all the datasets and use their name and icon for the legend. Filtering might be trickier. What we could do is augment the `fetchWPRDCData` function so that each `record` is given `.datasetName` field that corresponds to the dataset. That way we can filter out those not selected by the same dataset name shown in the legend. Does that make sense?
