### ISSUE TITLE
Sidebar: filter by date

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#38]
At least the WPRDC data has date information for sure. We should have some way to filter by date, even if it is just "today, last week, or last month". By default we show the last 30 days right now.

**Comment by coltonb** [comment]
Hey! I tried implementing this [here](https://github.com/Pitt-CSC/club_project_2017/pull/43).

**Comment by RitwikGupta** [comment]
Merged #43, this makes great progress!

**Comment by vonbearshark** [comment]
Awesome, @CJB124! Works really well. Would be nice to stylize it into the sidebar.
