### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#39]
We ought to have a header spanning across the top, especially once we come up with a name and logo (#23). It should probably connect right to the sidebar. If we decide to have separate tabs as Burgh's Eye view does, we should have some way to switch that here. If we don't have tabs, we could probably just add our name and logo to the sidebar.

**Comment by RitwikGupta** [comment]
Closed with 6b051805c63860945bd44dba498da711a14b22dc
