### ISSUE TITLE
Footer Overlaps Map Copyright Text on Mobile

### ISSUE THREAD

**Issue by nicoledaniels** [Pitt-CSC/club_project_2017#51]
On mobile (iPhone 7), the footer text overlaps with the copyright information on the Leaflet map

**Comment by RitwikGupta** [comment]
## For reference
![For reference](http://i.imgur.com/JjgydQE.jpg)

**Comment by jfw20** [comment]
Could the footer be moved bottom of the ui?  Just like stuck on the bottom of the box and resized?

**Comment by jfw20** [comment]
Pretty sure I can handle this.  Assign me if possible?

**Comment by vonbearshark** [comment]
Just sent an inv to become an organization member, then I can

**Comment by jfw20** [comment]
Is there a preference on just resizing the footer, or relocating it altogether possibly on mobile? I attempted making it vary in size by changing text size of it to various sizes with vmin unit, but seems too inconsistent and incredibly tiny by the time it is no longer overlapping with the copyright.  I'm not sure if the leaflet copyright can be moved/resized at all since I assume it is placed their by one of the unpkg.com scripts.

**Comment by vonbearshark** [comment]
We actually place the Leaflet copyright in `main.js` (https://github.com/Pitt-CSC/club_project_2017/blob/master/main.js#L29), so we can mess with it a little. Couldn't we stack them on mobile? Maybe give them both a CSS class we can mess with and stick one on top of the other?

**Comment by seifriedc** [comment]
Could we put our footer in the sidebar on mobile? Like at the bottom?

**Comment by vonbearshark** [comment]
^that could work for both mobile and desktop. It's starts contracted on mobile so it's not immediately visible, but .. meh.

**Comment by jfw20** [comment]
![image](https://cloud.githubusercontent.com/assets/16720541/22383860/af9bf83c-e499-11e6-8c17-83f89e5d2c79.png)


This is what it looks like with what I changed currently, does that look good, or do you think text is too small when footer is within sidebar?

**Comment by vonbearshark** [comment]
That looks perfect. What's it look like on mobile?

**Comment by jfw20** [comment]
Uh not sure best way to view fork changes on mobile?  I tried a git app but can't figure out a way to update it

**Comment by vonbearshark** [comment]
No worries, why don't you submit a PR and I'll check it out

**Comment by jfw20** [comment]
Tested w/ chromes mobile view option and text is still constrained inside of sidebar and copyright for leaftlet/google is clickable.  Appears to work
