### ISSUE TITLE
(ML) Visualize features (311)

### ISSUE THREAD

**Issue by RitwikGupta** [Pitt-CSC/club_project_2017#60]
Using `ml/data/data_311.json`, graph the data using any program of your choice. Find interesting fields and comment the visualizations in this issue.

**Comment by dzheng256** [comment]
![image](https://cloud.githubusercontent.com/assets/13357787/22301599/973eb6ea-e2f9-11e6-8eea-c7a1485dd6ea.png)
just made this graph, seems like almost all requests are from councils 3,6, and 8.

![image](https://cloud.githubusercontent.com/assets/13357787/22301949/e36dd7d4-e2fa-11e6-8686-1ac07024cd84.png)

Also created this one for neighborhoods.

**Comment by vonbearshark** [comment]
Are these just the most populated areas^?

**Comment by dzheng256** [comment]
it's for everything in the data file, which is only oakland

**Comment by RitwikGupta** [comment]
@dzheng256 I just noticed that the call made in the get_data_311 script limits to 100 rows only. You have to specify a large limit (like 999999) to make sure you get all the data.

**Comment by dzheng256** [comment]
ok, i'll check it out when i get a chance @RitwikGupta

**Comment by dzheng256** [comment]
made it 999999, new graphs. @RitwikGupta 
![image](https://cloud.githubusercontent.com/assets/13357787/22314661/73378a24-e330-11e6-985e-cb82ab40cf32.png)

It's actually 4783 oakland records, so 999,999 is more than enough.

**Comment by RitwikGupta** [comment]
Nice! How about analysis of the types of complaints?

**Comment by dzheng256** [comment]
195 unique complaints, trimmed it down to this by just choosing an arbitrary min of 30 complaints to make it on the plot
![image](https://cloud.githubusercontent.com/assets/13357787/22318064/94217f32-e345-11e6-8d8b-75f5d6c8c483.png)
might be able to group some stuff together. like there's "Graffiti, Removal" and "Graffiti, Documentation" and various traffic things etc that are all separate types of complaints

**Comment by vonbearshark** [comment]
Please make predictions for `Couch on Porch` so we can help the law enforcement stop these heinous atrocities

**Comment by RitwikGupta** [comment]
@dzheng256 Generally when conveying discrete data counts, you should sort the data so we can see the ranks. Good work though!

**Comment by dzheng256** [comment]
good point

**Comment by dzheng256** [comment]
![image](https://cloud.githubusercontent.com/assets/13357787/22318561/9cd5dab6-e349-11e6-893b-52d1ecc7d22b.png)
also changed x axis scale and changed min to 20
