### ISSUE TITLE
WPRDC data: Code violations

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#62]
Just like the 311 and city police data, the WPRDC offers a dataset for code violations for establishments, available here: https://data.wprdc.org/dataset/pittsburgh-pli-violations-report/resource/4e5374be-1a88-47f7-afee-6a79317019b4. Like the city police and 311 data, we just want the results from the past month.

**Comment by vonbearshark** [comment]
@brandonp728 , do you want to take a crack at this one now? You did that other one so quickly

**Comment by brandonp728** [comment]
@vonbearshark yeah, I'd like to!
