### ISSUE TITLE
WPRDC: Arrest Data

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#63]
Just like the 311 and city police data, the WPRDC offers a dataset for arrest information, available here: https://data.wprdc.org/dataset/arrest-data. Like the city police and 311 data, we just want the results from the past month. We also want to be sure this doesn't overlap with the police blotter we have. It doesn't seem that it does.

**Comment by brandonp728** [comment]
Hey, I'd like to give this issue a try!

**Comment by vonbearshark** [comment]
All yours, @brandonp728 ! Thanks! Let me know if you need any help at all
