### ISSUE TITLE
WPRDC: Non-traffic violation data 

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#64]
The WPRDC provides a dataset for non-traffic citations (NTCs, also known as "summary offenses") document low-level criminal offenses where a law enforcement officer or other authorized official issued a citation in lieu of arrest, available here: https://data.wprdc.org/dataset/non-traffic-citations. We need to pull this in just like the 311 and police data, getting the results from the past month. We should make sure this doesn't overlap with any other police data we're getting. It doesn't seem like it is.

**Comment by ghost** [comment]
Could I take this one @vonbearshark ? I'm relatively new to javascript, so it may not be perfect but I think I can do it.

**Comment by vonbearshark** [comment]
I think you can, too @GavinFreud ! Let me know if you need any guidance at all. Make sure to pull the most recent changes first because we've updated how we're calling the data

**Comment by ghost** [comment]
@vonbearshark should I make a new icon for this?

**Comment by vonbearshark** [comment]
Yeah take a look how we implement the others, as well as Font Awesome: http://fontawesome.io/icons/, you can pick one of those and a color, essentially
