### ISSUE TITLE
Sidebar Blocks Most of the Map

### ISSUE THREAD

**Issue by nicoledaniels** [Pitt-CSC/club_project_2017#66]
On mobile (iPhone 7), the sidebar with the date information covers a majority of the map. The user is unable to click on pins that are under this sidebar. 

### Possible solution:
Sidebar should be able to be expanded and contracted, and it's contracted by default on mobile.

![image uploaded from ios](https://cloud.githubusercontent.com/assets/5464799/22296193/62a0f446-e2e7-11e6-8c2f-fbdabfaff961.jpg)

**Comment by vonbearshark** [comment]
Yeah, I think for mobile the sidebar can either be expanded to take up the whole screen or completely contracted. It looks sloppy if there's a sliver of an unusable map on mobile
