### ISSUE TITLE
WPRDC: library data

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#68]
This should be super simple. The WPRDC gives information on Carnegie libraries. We only have one in Oakland, but it would be nice to map it with the hours and address (also provided). It's available here: https://data.wprdc.org/dataset/libraries. We can use the same icons as the WPRDC does in its example.

**Comment by chrisski44** [comment]
@vonbearshark I'll pick this one up!

**Comment by vonbearshark** [comment]
Thanks, @chrisski44 ! I just sent you an email invite to become a collaborator. If you accept, I can assign you to this issue.

Don't forget to add your name to our `contributors.md` file, too!

Let me know if you need any help at all. For this Issue, take a look at the calls already in the `main.js` that connect to the city and 311 data; the call you're making should be super similar.

**Comment by chrisski44** [comment]
@vonbearshark whats the best way to get the icons? I tried to save it off the website but it doesn't look very good.

**Comment by brlodi** [comment]
Their Twitter profile picture is basically the same, if we want to just scale that down. https://pbs.twimg.com/profile_images/423885276012765185/Debf9xoF.jpeg

**Comment by chrisski44** [comment]
awesome thanks! I'll check out the dimensions of the other pins and scale it down

**Comment by brlodi** [comment]
The map pins are all nominally 32x32 (and the retina versions are 64x64)

**Comment by brlodi** [comment]
Also I might make a pin-shaped one as part of my divIcon work, so we can replace it then.

**Comment by vonbearshark** [comment]
Yeah, that was my next question: could this hook in with Fontello, @brlodi?

**Comment by vonbearshark** [comment]
Closed by #78, but we'll want to swap this out for an icon like we mentioned later. Also, I'd like to update the HTML when we have a proper style for the pop-up descriptions.

Thanks, @chrisski44!

**Comment by brlodi** [comment]
@vonbearshark I can probably recreate the CLP logo as an SVG to stick in the font. At that size we might have to lose the coloration to keep it readable, though. I'll see what I can do.
