### ISSUE TITLE
Map copyright links not interactable

### ISSUE THREAD

**Issue by brlodi** [Pitt-CSC/club_project_2017#76]
Currently the Leaflet and OpenStreetMap links in the copyright notice don't work because the 100% width footer is covering them. Related to #51, but more important to resolve short-term.

**Comment by vonbearshark** [comment]
@jfw20 , could you take a look at this, too? I can assign you. You should be able to do both in one commit.

**Comment by jfw20** [comment]
Yea that's fine

**Comment by jfw20** [comment]
This should also be closed now, #51 fix also fixed this, should have added that in commit, my bad.

**Comment by vonbearshark** [comment]
Yeah, I added this to the merge message, but it didn't close this. I must not have used the right syntax. Thanks again, @jfw20!
