### ISSUE TITLE
ES6 String Interpolation

### ISSUE THREAD

**Issue by mbilker** [Pitt-CSC/club_project_2017#80]
For ES6 features, this project is using arrow functions, string interpolation, fetch requests, and promises. Promises and `fetch` requests were fixed by using polyfills, but what about browser support for the other features in use?

**Comment by brlodi** [comment]
The main browsers at fault seem to be IE11 and Android. For reference: http://kangax.github.io/compat-table/es6/

**Comment by vonbearshark** [comment]
Good question. Our stance here is not to worry about this for now. For clarity and development speed, implement everything how you'd like. We'll cross that bridge later with either shims or maybe with a compilation step for production.

**Comment by mbilker** [comment]
Thank you very much!
