### ISSUE TITLE
Re-styled Header

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#88]
We should stylize the header to make it a little more attractive. Also, we should reference our new name: PantherView! If we can stylize the date filter selector in the UI, too, we should. Something like this: http://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_button_group_justified&stacked=h, but white on blue. This all means selecting colors and fonts that we should use throughout the whole site

**Comment by vonbearshark** [comment]
Just update the `title` tag in HTML, too, with the new name

**Comment by nehaabraham** [comment]
I'd like to take this on, not sure how to assign myself to it.

**Comment by vonbearshark** [comment]
Just sent you an invitation to be a collaborator--if you accept I can assign you!

**Comment by vonbearshark** [comment]
Also, @alexandrabush is working on a logo. It would be great to include that in the header, too, when she finishes it (no rush)

**Comment by nehaabraham** [comment]
@alexandrabush did a lovely job with the WiCS logo, she'll be great for this :)
