### ISSUE TITLE
lunch rush livestream

### ISSUE THREAD

**Issue by kaidawkins** [Pitt-CSC/club_project_2017#96]
this feature could possibly be out of scope for this semester, but the idea is to add a feature to the map that'll somehow show a user how busy a specific on-campus/off-campus restaurant is. it would eliminate the problem of bouncing around from one eatery to another trying to find a place where you can get lunch in a decent amount of time. we would need to somehow gain access to data from interested businesses.

**Comment by vonbearshark** [comment]
This is a great idea. I emailed NoWait to see if we could get access to some of its data, but I'm not hopeful. Might need to do another route.

**Comment by RitwikGupta** [comment]
Yelp bought NoWait, so there's no chance of getting that data

**Comment by vonbearshark** [comment]
Sad face. We could have a check-in system from our app, but that's a lot to support on our end. Maybe we could start with Pitt food places, like market, first--do you think we can get live swipe data?

**Comment by brlodi** [comment]
@RitwikGupta they didn't buy NoWait (that I can see), but I doubt the integration agreement is in our favor. (That scared me; I use NoWait all the time but I refuse to use Yelp on principle)

**Comment by RitwikGupta** [comment]
I believe it's a "partnership", but many of the NoWait execs left when this partnership happened because of what's rumored to be a disagreement over the way the partnership was basically structured as a takeover.

**Comment by brlodi** [comment]
Well at least I continue to feel justified in hating Yelp. I was a host at one of NoWait's pilot restaurants so I helped (from the user side) get the restaurant-facing app in order. I think I was the only technical user they had at the time because I answered a lot of UX questions.

**Comment by kaidawkins** [comment]
yeah i was def thinking it would be easier to gather data from on campus places first before we got data from the surrounding restaurants!

**Comment by vonbearshark** [comment]
Does anyone know if there's a live swipes feed or anything with Market?

**Comment by kaidawkins** [comment]
have y'all seen this? https://github.com/Pitt-CSC/PittAPI/issues/11 i assume you have it was on the slack, it's a major help

**Comment by vonbearshark** [comment]
Yeah that's neat, but that's only the hours

**Comment by kaidawkins** [comment]
that could be a start tho

**Comment by RitwikGupta** [comment]
Market swipes are tracked by Blackboard, we don't have any access to that, it's a closed system

**Comment by vonbearshark** [comment]
In that we could _never_ have access? Or if we bug them enough they might let us?

**Comment by kaidawkins** [comment]
damn they won't give us _access at all_?

**Comment by RitwikGupta** [comment]
Pitt hates giving data out. In this case, you'd usually file a FOIA/RTK, but Pitt is waived from any FOIA/RTK requests by the fact that they're a state-related school. I've filed one myself and you get a nice letter from a lawyer.

**Comment by RitwikGupta** [comment]
This is the reason why the PittAPI is so hacky and backdoor-y
